// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package greeterworld represents the world "component:hello/greeter-world".
//
// An example world for the component to target.
package greeterworld
