// Code generated by wit-bindgen-go. DO NOT EDIT.

package greeter

// Exports represents the caller-defined exports from "component:hello/greeter".
var Exports struct {
	// SayHello represents the caller-defined, exported function "say-hello".
	//
	//	say-hello: func(name: string) -> string
	SayHello func(name string) (result string)
}
