// Code generated by wit-bindgen-go. DO NOT EDIT.

package greeter

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "component:hello".

//go:wasmexport component:hello/greeter#say-hello
//export component:hello/greeter#say-hello
func wasmexport_SayHello(name0 *uint8, name1 uint32) (result *string) {
	name := cm.LiftString[string]((*uint8)(name0), (uint32)(name1))
	result_ := Exports.SayHello(name)
	result = &result_
	return
}
